# Vectorization
## why to vectorize

In [7]:
import numpy as np
np.random.seed(101)
numElem = 1000000;
a = np.random.rand(numElem)
np.random.seed(102)
b = np.random.rand(numElem)
print("a = ", a,'\nb = ',b)

a =  [0.51639863 0.57066759 0.02847423 ... 0.08746427 0.54645473 0.9239232 ] 
b =  [0.59768158 0.6759869  0.29928174 ... 0.39269038 0.65046064 0.29465185]


In [8]:
import time
tic = time.time()
c = np.dot(a,b)
toc = time.time()
vec_time = toc-tic;
print(c)
print("Vectorized version:", str(1000*(vec_time)), " ms")

249630.3528377748
Vectorized version: 6.98399543762207  ms


In [13]:
tic = time.time()
c = 0;
for i in range(numElem):
    c += a[i]*b[i]
toc = time.time()
loop_time = toc-tic
print(c)
print("For loop version:", str(1000*(loop_time)), " ms")
print("vectorized dot product is " + str(int(loop_time//vec_time)) + "x faster then for loop dot product")

249630.35283777452
For loop version: 739.0241622924805  ms
vectorized dot product is 105x faster then for loop dot product


## broadcasting

In [15]:
z = np.zeros((10,2)).T  transpose
print(z)
z.shape

NameError: name 'transpose' is not defined

In [11]:
d = np.random.rand(10).reshape(2,5)
print(d)

[[0.96114072 0.04760622 0.76740468 0.6771542  0.8898101 ]
 [0.71411727 0.68242519 0.94151206 0.51779182 0.80722234]]


In [32]:
e = np.array([[1, 1, 1],
              [2, 3, 4]])

In [35]:
sum_e = e.sum(axis=1)
print("axis 0", e.sum(axis=0))
print("axis 1", e.sum(axis=1))
print("axis 2", e.sum())

axis 0 [3 4 5]
axis 1 [3 9]
axis 2 12


## Numpy Arrays

In [138]:
# 1D arrays
arr1D = np.array([1,2,3])
# 2D arrays
arr2D = np.array([[1,2,3],
                  [4,5,6]])
arr3D = np.array([[[1,2,3],
                  [4,5,6]],[1,2,3],
                  [4,5,6]])
print("1D array: \n", arr1D)
print("2D array: \n", arr2D)
print("3D array: \n", arr3D)

1D array: 
 [1 2 3]
2D array: 
 [[1 2 3]
 [4 5 6]]
3D array: 
 [list([[1, 2, 3], [4, 5, 6]]) list([1, 2, 3]) list([4, 5, 6])]


In [144]:
# np.insert(arr1D,0,[9,9])
np.insert(arr2D,0,[9,8],axis=1)

array([[9, 1, 2, 3],
       [8, 4, 5, 6]])

In [145]:
np.insert(arr2D,0,[9,8,7],axis=0)

array([[9, 8, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [146]:
np.append(arr2D,[[9,8,7]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [150]:
b = np.array([[9,8]]).T
np.append(arr2D,b,axis=1)

array([[1, 2, 3, 9],
       [4, 5, 6, 8]])

In [152]:
# or 
np.append(arr2D,[[9],[8]],axis=1)

array([[1, 2, 3, 9],
       [4, 5, 6, 8]])

## Broadcasting

In [185]:
np.arange(0,6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
x+np.array([10,20,30])

array([[10, 21, 32],
       [13, 24, 35]])

In [188]:
x+np.array([[10,20]]).T

array([[10, 11, 12],
       [23, 24, 25]])

In [201]:
np.array([[10,20,30]]).T

array([[10],
       [20],
       [30]])